require("dotenv").config();
const mongoose = require("mongoose");
const Product = require("../models/Product");

const products = [
  {
    name: "Pink Paradise Diamond Drop Earrings",
    category: "Imitation Jewellery",
    description: "A soft pink drop-earring design with bridal shine, lightweight wear, and a polished finish suited for festive outfits and evening styling.",
    price: 2499,
    salePrice: 1999,
    stock: 14,
    image: "1771416370369-Pink Paradise Diamond Drop Earrings.webp",
    arImage: "1771416370371-Pink Paradise Diamond Drop Earrings_AR.png",
    arType: "earring",
    rating: 4.8,
  },
  {
    name: "Sculpted Flower Diamond Stud Earrings",
    category: "Imitation Jewellery",
    description: "Floral stud earrings with a bright stone arrangement designed for daily elegance, gifting, and subtle festive styling.",
    price: 1799,
    salePrice: 1499,
    stock: 18,
    image: "1771416626615-Sculpted Flower Diamond Stud Earrings.webp",
    arImage: "1771416626616-Sculpted Flower Diamond Stud Earrings_AR.png",
    arType: "earring",
    rating: 4.6,
  },
  {
    name: "Heart Harmony Diamond Stud Earrings",
    category: "Imitation Jewellery",
    description: "Heart-shaped stud earrings finished with clean sparkle and a compact profile that works across casual and traditional looks.",
    price: 1899,
    salePrice: 1599,
    stock: 16,
    image: "1771416868769-Heart Harmony Diamond Stud Earrings.webp",
    arImage: "1771416868770-Heart Harmony Diamond Stud Earrings_AR.png",
    arType: "earring",
    rating: 4.7,
  },
  {
    name: "Love Spark Diamond Drop Earrings",
    category: "Imitation Jewellery",
    description: "Long-form drop earrings with movement, shine, and a boutique bridal profile designed for receptions and portrait-friendly styling.",
    price: 2899,
    salePrice: 2299,
    stock: 11,
    image: "1771417565578-Love Spark Diamond Earrings Diamond Drop Earrings.webp",
    arImage: "1771417565579-Love Spark Diamond Earrings Diamond Drop Earrings_AR.png",
    arType: "earring",
    rating: 4.9,
  },
  {
    name: "Radiant Orbit Chain",
    category: "Golden Covering Jewellery",
    description: "A graceful chain with a clean circular pendant silhouette and premium boutique finish for layering or standalone styling.",
    price: 3299,
    salePrice: 2799,
    stock: 13,
    image: "1771416104751-Radiant chain.jpg",
    arImage: "1771416104752-Radiant Orbit Chain_AR.png",
    arType: "chain",
    rating: 4.7,
  },
  {
    name: "Blushing Glow Diamond Necklace",
    category: "Bridal Jewellery for Rent",
    description: "A bridal necklace with blush-toned brilliance, balanced detailing, and a premium silhouette suited for engagement and wedding sets.",
    price: 6999,
    salePrice: 5799,
    stock: 6,
    image: "1771415857700-Blushing Glow Diamond Necklace.jpg",
    arImage: "1771415857701-Blushing Glow Diamond Necklace_AR.png",
    arType: "chain",
    rating: 4.9,
  },
  {
    name: "Wing Crest Diamond Necklace",
    category: "Bridal Jewellery for Rent",
    description: "A structured bridal necklace with wing-inspired stone placement, statement sparkle, and elevated ceremonial presence.",
    price: 7499,
    salePrice: 6199,
    stock: 5,
    image: "1771415566920-Wing Crest Diamond Necklace.jpg",
    arImage: "1771415566921-Wing Crest Diamond Necklace_AR.png",
    arType: "chain",
    rating: 4.8,
  },
  {
    name: "Soaring Wing Diamond Necklace",
    category: "Bridal Jewellery for Rent",
    description: "A dramatic bridal necklace made for full-set styling, photography-ready shine, and standout wedding reception looks.",
    price: 7899,
    salePrice: 6499,
    stock: 4,
    image: "1771414985630-Soaring Wing Diamond Necklace.jpg",
    arImage: "1771414985631-Soaring Wing Diamond Necklace_AR.png",
    arType: "chain",
    rating: 4.9,
  },
  {
    name: "Ethereal Wing Diamond Necklace",
    category: "Impon Jewellery",
    description: "A refined necklace with airy wing-like contours, polished stones, and an elegant boutique finish for festive dressing.",
    price: 4699,
    salePrice: 3999,
    stock: 9,
    image: "1771417400088-Ethereal Wing Diamond Necklace.webp",
    arImage: "1771417400088-Ethereal Wing Diamond Necklace_AR.png",
    arType: "chain",
    rating: 4.7,
  },
  {
    name: "Rose Bloom Bridal Bangle Set",
    category: "Bridal Bangles",
    description: "A coordinated bridal bangle set with warm rose accents, layered shine, and a rich festive finish built for stacked wear.",
    price: 3599,
    salePrice: 2999,
    stock: 12,
    image: "1771145941725-primajewel1.webp",
    rating: 4.5,
  },
  {
    name: "Velvet Petal Hair Clip",
    category: "Hair Accessories",
    description: "A boutique floral hair clip that adds a soft statement to braids, buns, and festive half-up styling.",
    price: 899,
    salePrice: 699,
    stock: 24,
    image: "1771145941725-primajewel1.webp",
    rating: 4.4,
  },
  {
    name: "Pearl Bloom Return Gift Box",
    category: "Gifts",
    description: "An elegant gift-ready accessory set with boutique presentation, suitable for bridal return gifts and festive hampers.",
    price: 1299,
    salePrice: 999,
    stock: 20,
    image: "1771416370369-Pink Paradise Diamond Drop Earrings.webp",
    rating: 4.5,
  },
  {
    name: "Festival Charm Kids Bracelet",
    category: "Toys",
    description: "A playful bracelet set with colorful detailing and safe lightweight construction for festive gifting to children.",
    price: 699,
    salePrice: 549,
    stock: 22,
    image: "1771416626615-Sculpted Flower Diamond Stud Earrings.webp",
    rating: 4.3,
  },
  {
    name: "Golden Aura Temple Chain",
    category: "Golden Covering Jewellery",
    description: "Temple-inspired chain styling with boutique gold-tone finish, suited for sarees, celebrations, and layered traditional looks.",
    price: 3899,
    salePrice: 3299,
    stock: 10,
    image: "1771416104751-Radiant chain.jpg",
    rating: 4.6,
  },
  {
    name: "Classic Bridal Rental Set",
    category: "Bridal Jewellery for Rent",
    description: "A full bridal rental-inspired necklace look offering ceremonial scale, warm stonework, and high-impact boutique finish.",
    price: 8199,
    salePrice: 6899,
    stock: 3,
    image: "1771415566920-Wing Crest Diamond Necklace.jpg",
    rating: 4.8,
  },
  {
    name: "Emerald Bloom Fancy Pendant",
    category: "Fancy Products",
    description: "A boutique pendant with clean stone detailing and a fresh green-accented aesthetic for casual and festive styling.",
    price: 1599,
    salePrice: 1299,
    stock: 17,
    image: "1771417400088-Ethereal Wing Diamond Necklace.webp",
    rating: 4.4,
  },
  {
    name: "Lotus Shine Impon Necklace",
    category: "Impon Jewellery",
    description: "An impon-inspired necklace with a warm traditional profile, balanced weight, and versatile festive elegance.",
    price: 4299,
    salePrice: 3699,
    stock: 8,
    image: "1771415857700-Blushing Glow Diamond Necklace.jpg",
    rating: 4.7,
  },
  {
    name: "Bridal Glow Statement Studs",
    category: "Imitation Jewellery",
    description: "Statement studs designed for bridal and festive wear with reflective stones, compact comfort, and a premium boutique finish.",
    price: 2099,
    salePrice: 1699,
    stock: 15,
    image: "1771416868769-Heart Harmony Diamond Stud Earrings.webp",
    rating: 4.5,
  },
  {
    name: "Rosewood Evening Maxi Dress",
    category: "Boutique Dresses",
    description: "A flowing boutique maxi dress with a soft rosewood tone, structured waist, and elegant drape for festive evenings and special dinners.",
    price: 4599,
    salePrice: 3899,
    stock: 9,
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80",
    rating: 4.7,
  },
  {
    name: "Ivory Bloom Anarkali Dress",
    category: "Boutique Dresses",
    description: "An ivory-toned anarkali with graceful flare, subtle texture, and a polished silhouette suited for boutique festive dressing.",
    price: 4999,
    salePrice: 4299,
    stock: 7,
    image: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=900&q=80",
    rating: 4.8,
  },
  {
    name: "Midnight Satin Occasion Dress",
    category: "Boutique Dresses",
    description: "A satin occasion dress with a clean midnight finish, flattering cut, and understated premium styling for evening events.",
    price: 4399,
    salePrice: 3699,
    stock: 8,
    image: "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&q=80",
    rating: 4.6,
  },
  {
    name: "Crescent Quilted Boutique Handbag",
    category: "Handbags",
    description: "A quilted crescent handbag with a structured profile, boutique hardware accents, and enough room for everyday essentials.",
    price: 2899,
    salePrice: 2399,
    stock: 14,
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=80",
    rating: 4.7,
  },
  {
    name: "Mocha Luxe Shoulder Bag",
    category: "Handbags",
    description: "A warm mocha shoulder bag with a clean silhouette and boutique finish that pairs well with both western and festive outfits.",
    price: 3199,
    salePrice: 2699,
    stock: 12,
    image: "https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=900&q=80",
    rating: 4.6,
  },
  {
    name: "Pearl Clasp Mini Party Bag",
    category: "Handbags",
    description: "A compact party bag with a pearl-inspired clasp, polished boutique detailing, and an elegant evening-ready finish.",
    price: 2499,
    salePrice: 2099,
    stock: 10,
    image: "https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?auto=format&fit=crop&w=900&q=80",
    rating: 4.5,
  },
  {
    name: "Nude Stride Block Heels",
    category: "Footwear",
    description: "Boutique block heels in a versatile nude tone with stable comfort, clean lines, and occasion-friendly polish.",
    price: 2699,
    salePrice: 2199,
    stock: 13,
    image: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=900&q=80",
    rating: 4.5,
  },
  {
    name: "Velvet Bow Festive Flats",
    category: "Footwear",
    description: "Soft festive flats with a velvet bow detail and a boutique finish designed for long wear with elevated comfort.",
    price: 1899,
    salePrice: 1499,
    stock: 18,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80",
    rating: 4.4,
  },
  {
    name: "Bronze Gleam Occasion Sandals",
    category: "Footwear",
    description: "A refined sandal pair with bronze-toned shine and boutique evening styling for dresses, sarees, and festive sets.",
    price: 2399,
    salePrice: 1999,
    stock: 11,
    image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=900&q=80",
    rating: 4.5,
  },
  {
    name: "Petal Print Boutique Scarf",
    category: "Scarves",
    description: "A lightweight printed scarf with soft petal-inspired tones that adds a polished boutique accent to simple outfits.",
    price: 1199,
    salePrice: 899,
    stock: 20,
    image: "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?auto=format&fit=crop&w=900&q=80",
    rating: 4.4,
  },
  {
    name: "Sand Drape Everyday Scarf",
    category: "Scarves",
    description: "An everyday scarf in a soft sand tone with an easy drape, smooth feel, and versatile boutique styling.",
    price: 1099,
    salePrice: 849,
    stock: 19,
    image: "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?auto=format&fit=crop&w=900&q=80",
    rating: 4.3,
  },
  {
    name: "Golden Edge Silk Scarf",
    category: "Scarves",
    description: "A silk-touch scarf with golden edge detailing and an elegant boutique finish for layering over dresses and occasion looks.",
    price: 1499,
    salePrice: 1199,
    stock: 15,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80",
    rating: 4.6,
  },
  {
    name: "Pearl Accent Waist Belt",
    category: "Fashion Accessories",
    description: "A boutique waist belt with pearl accents and a polished clasp, designed to elevate dresses and occasion outfits.",
    price: 1399,
    salePrice: 1099,
    stock: 16,
    image: "https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=900&q=80",
    rating: 4.4,
  },
  {
    name: "Classic Oval Sunglasses",
    category: "Fashion Accessories",
    description: "Elegant oval sunglasses with a boutique profile, everyday comfort, and a refined finish that suits multiple looks.",
    price: 1699,
    salePrice: 1299,
    stock: 21,
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=900&q=80",
    rating: 4.5,
  },
  {
    name: "Signature Hair Bow Set",
    category: "Fashion Accessories",
    description: "A coordinated hair bow set with boutique textures and soft neutral shades for polished daywear and gifting.",
    price: 899,
    salePrice: 699,
    stock: 23,
    image: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80",
    rating: 4.3,
  },
];

const buildReviews = (name) => [
  {
    userName: "Ananya",
    userEmail: `${name.toLowerCase().replace(/[^a-z0-9]+/g, "")}@review.prima`,
    rating: 5,
    comment: "Finishing quality is excellent and the boutique styling looks premium in person.",
  },
  {
    userName: "Meera",
    userEmail: `${name.toLowerCase().replace(/[^a-z0-9]+/g, "")}-2@review.prima`,
    rating: 4,
    comment: "Beautiful product and good value for festive shopping.",
  },
];

const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URL);

    for (const item of products) {
      const reviews = buildReviews(item.name);
      const imageList = [item.image].filter(Boolean);

      await Product.findOneAndUpdate(
        { name: item.name },
        {
          ...item,
          images: imageList,
          reviews,
        },
        { upsert: true, returnDocument: "after", setDefaultsOnInsert: true }
      );
    }

    console.log(`Seeded ${products.length} boutique products.`);
    process.exit(0);
  } catch (error) {
    console.error("Product seed failed:", error.message);
    process.exit(1);
  }
};

seed();
